name: Android APK Build

on:
  push:
    branches: [ "main" ] # 코드가 업데이트 될 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest # 깃허브의 깨끗한 리눅스 서버 대여

    steps:
    - uses: actions/checkout@v4 # v3 대신 최신 v4 사용 권장

    - name: Node.js 셋업
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Java 셋업 (여기서 자바 에러가 완벽히 해결됨)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: 모듈 설치 및 동기화 (Node.js 명령어)
      run: |
        npm install
        npx cap sync android

    - name: APK 빌드 (Gradle)
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug

    - name: APK 파일 업로드 (Artifact)
      uses: actions/upload-artifact@v4  # v3 대신 최신 v4 사용 권장
      with:
        name: app-debug-apk            # 다운로드될 파일 압축 이름
        path: android/app/build/outputs/apk/debug/app-debug.apk # APK 파일의 정확한 경로
